version: "3.9"
services:
  frontend:
    image: frontend_image
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./FrontEnd
    ports: 
      - 3000:3000
    environment:
      - MESSAGE="Building FrontEnd"
    
  database:
    image: database_image
    container_name: database
    restart: unless-stopped
    build:
      context: ./Database
    ports: 
      - 8000:8000
    environment:
      - MESSAGE="Building Database"

  # auth:
  #   restart: unless-stopped
  #   build:
  #     context: ./Authentication
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - MESSAGE="Building Authentication"

  # daterecommender:
  #   restart: unless-stopped
  #   build:
  #     context: ./DateRecommender
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     - MESSAGE="Building DateRecommender"

  # profilebackend:
  #   restart: unless-stopped
  #   build:
  #     context: ./ProfileBackend
  #   ports:
  #     - "5002:5000"
  #   environment:
  #     - MESSAGE="Building ProfileBackend"

  textchat:
    image: textchatimage
    container_name: textchat
    restart: unless-stopped
    build:
      context: ./TextChat
    # expose:
    #    - "5000"
    ports:
      - "5003:5000"
    environment:
      - MESSAGE="Building TextChat"
    # networks:
    #   app_net:
    #     ipv4_address: 172.16.238.10

  # swipe:
  #   restart: unless-stopped
  #   build:
  #     context: ./Swiping
  #   ports:
  #     - "5004:5000"
  #   environment:
  #     - MESSAGE="Building Authentication"

  nginx:
    image: nginximage
    container_name: nginx
    restart: always
    build:
      context: ./APIGateWay
    ports:
      - "8080:80"
    links:
      - textchat
    depends_on:
      # - auth
      # - daterecommender
      # - profilebackend
      - textchat
      # - swipe
      