services:
  # auth:
  #   restart: unless-stopped
  #   build:
  #     context: ./Authentication
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - MESSAGE="Building Authentication"

  # daterecommender:
  #   restart: unless-stopped
  #   build:
  #     context: ./DateRecommender
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     - MESSAGE="Building DateRecommender"

  # profilebackend:
  #   restart: unless-stopped
  #   build:
  #     context: ./ProfileBackend
  #   ports:
  #     - "5002:5000"
  #   environment:
  #     - MESSAGE="Building ProfileBackend"

  textchat:
    image: node:alpine
    restart: unless-stopped
    build:
      context: ./TextChat
    ports:
      - "5003:5000"
    environment:
      - MESSAGE="Building TextChat"

  # swipe:
  #   restart: unless-stopped
  #   build:
  #     context: ./Swiping
  #   ports:
  #     - "5004:5000"
  #   environment:
  #     - MESSAGE="Building Authentication"

  nginx:
    image: nginx:alpine
    restart: always
    build:
      context: ./APIGateWay
    ports:
      - "8080:80"
    depends_on:
      # - auth
      # - daterecommender
      # - profilebackend
      - textchat
      # - swipe
      