version: "3.9"
services:
  # auth:
  #   restart: unless-stopped
  #   build:
  #     context: ./Authentication
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - MESSAGE="Building Authentication"

  # daterecommender:
  #   restart: unless-stopped
  #   build:
  #     context: ./DateRecommender
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     - MESSAGE="Building DateRecommender"

  # profilebackend:
  #   restart: unless-stopped
  #   build:
  #     context: ./ProfileBackend
  #   ports:
  #     - "5002:5000"
  #   environment:
  #     - MESSAGE="Building ProfileBackend"

  textchat:
    image: textchatimage
    container_name: textchat
    restart: unless-stopped
    expose:
      - "5000"
    build:
      context: ./TextChat
    environment:
      - MESSAGE="Building TextChat"
    # networks:
    #   app_net:
    #     ipv4_address: 172.16.238.10

  # swipe:
  #   restart: unless-stopped
  #   build:
  #     context: ./Swiping
  #   ports:
  #     - "5004:5000"
  #   environment:
  #     - MESSAGE="Building Authentication"

  nginx:
    image: nginximage
    container_name: nginx
    restart: always
    build:
      context: ./APIGateWay
    ports:
      - "8080:80"
    depends_on:
      # - auth
      # - daterecommender
      # - profilebackend
      - textchat
      # - swipe
      