FROM nginx
COPY default.conf /etc/nginx/conf.d/default.conf


EXPOSE 80
# COPY ./package.json ./
# COPY ./package-lock.json ./


# COPY public /usr/share/nginx/html/public
# COPY node_modules ./node_modules